### PR TITLE
OSGi Support - manual

### PR DESCRIPTION
**Pull request by stbischof**
- generate Bundle-Manifests using manual description
- export packages to use for others
- ServiceLoader
  - add OSGI-Metadata for Services
  - add Require-Cap (osgi.service.processor and registrar)

Core Manifest - Print-Mode:
```
[MANIFEST]

Build-Jdk-Spec                          22
Bundle-Description                      Java Rule Engine
Bundle-DocURL                           https://www.evrete.org/evrete-core
Bundle-License                          "MIT License";link="https://www.opensource.org/licenses/mit-license"
Bundle-ManifestVersion                  2
Bundle-Name                             evrete-core
Bundle-SCM                              connection="scm:git:https://github.com/evrete/evrete.git/evrete-core"
                                        developer-connection="scm:git:https://github.com/evrete/evrete.git/evrete-core"
                                        tag=HEAD
                                        url="https://github.com/evrete/evrete/evrete-core"
Bundle-SymbolicName                     evrete-core
Bundle-Version                          3.0.7.202402081653
Created-By                              Maven JAR Plugin 3.3.0
Export-Package                          org.evrete.api.annotations;version="3.0.7"
                                        org.evrete.api.spi;uses:="org.evrete,org.evrete.api,org.evrete.runtime.compiler";version="3.0.7"
                                        org.evrete.api;uses:="org.evrete,org.evrete.runtime,org.evrete.runtime.compiler";version="3.0.7"
                                        org.evrete.collections;uses:="org.evrete.api";version="3.0.7"
                                        org.evrete.runtime.async;uses:="org.evrete.runtime,org.evrete.runtime.evaluation,org.evrete.util";version="3.0.7"
                                        org.evrete.runtime.compiler;uses:="javax.lang.model.element,javax.tools,org.evrete.api";version="3.0.7"
                                        org.evrete.runtime.evaluation;uses:="org.evrete.api,org.evrete.runtime,org.evrete.util";version="3.0.7"
                                        org.evrete.runtime;uses:="org.evrete,org.evrete.api,org.evrete.collections,org.evrete.runtime.compiler,org.evrete.runtime.evaluation,org.evrete.util";version="3.0.7"
                                        org.evrete.spi.minimal;uses:="org.evrete.api,org.evrete.api.spi,org.evrete.runtime.compiler";version="3.0.7"
                                        org.evrete.util;uses:="org.evrete,org.evrete.api,org.evrete.runtime,org.evrete.runtime.evaluation";version="3.0.7"
                                        org.evrete;uses:="org.evrete.api,org.evrete.api.spi,org.evrete.runtime.async";version="3.0.7"
Implementation-Title                    Java Rule Engine
Implementation-URL                      https://www.evrete.org
Implementation-Version                  3.0.07-SNAPSHOT
Import-Package                          javax.lang.model.element
                                        javax.tools
                                        org.evrete
                                        org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.collections
                                        org.evrete.runtime
                                        org.evrete.runtime.async
                                        org.evrete.runtime.compiler
                                        org.evrete.runtime.evaluation
                                        org.evrete.util
Manifest-Version                        1.0
Provide-Capability                      osgi.service;objectClass:List<String>="org.evrete.api.spi.ExpressionResolverProvider";effective:=active
                                        osgi.service;objectClass:List<String>="org.evrete.api.spi.LiteralRhsCompiler";effective:=active
                                        osgi.service;objectClass:List<String>="org.evrete.api.spi.MemoryFactoryProvider";effective:=active
                                        osgi.service;objectClass:List<String>="org.evrete.api.spi.TypeResolverProvider";effective:=active
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.ExpressionResolverProvider";register:="org.evrete.spi.minimal.DefaultExpressionResolverProvider"
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.LiteralRhsCompiler";register:="org.evrete.spi.minimal.DefaultLiteralRhsCompiler"
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.MemoryFactoryProvider";register:="org.evrete.spi.minimal.DefaultMemoryFactoryProvider"
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.TypeResolverProvider";register:="org.evrete.spi.minimal.DefaultTypeResolverProvider"
Require-Capability                      osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
                                        osgi.extender;filter:="(&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0)))"
                                        osgi.extender;filter:="(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!(version>=2.0.0)))"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.DSLKnowledgeProvider)";osgi.serviceloader="org.evrete.api.spi.DSLKnowledgeProvider"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.ExpressionResolverProvider)";osgi.serviceloader="org.evrete.api.spi.ExpressionResolverProvider"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.LiteralRhsCompiler)";osgi.serviceloader="org.evrete.api.spi.LiteralRhsCompiler"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.MemoryFactoryProvider)";osgi.serviceloader="org.evrete.api.spi.MemoryFactoryProvider"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.TypeResolverProvider)";osgi.serviceloader="org.evrete.api.spi.TypeResolverProvider"
SPDX-License-Identifier                 MIT License


[IMPEXP]

Import-Package
  javax.lang.model.element               
  javax.tools                            
  org.evrete                             
  org.evrete.api                         
  org.evrete.api.spi                     
  org.evrete.collections                 
  org.evrete.runtime                     
  org.evrete.runtime.async               
  org.evrete.runtime.compiler            
  org.evrete.runtime.evaluation          
  org.evrete.util                        

Export-Package
  org.evrete                             {version=3.0.7}
  org.evrete.api                         {version=3.0.7}
  org.evrete.api.annotations             {version=3.0.7}
  org.evrete.api.spi                     {version=3.0.7}
  org.evrete.collections                 {version=3.0.7}
  org.evrete.runtime                     {version=3.0.7}
  org.evrete.runtime.async               {version=3.0.7}
  org.evrete.runtime.compiler            {version=3.0.7}
  org.evrete.runtime.evaluation          {version=3.0.7}
  org.evrete.spi.minimal                 {version=3.0.7}
  org.evrete.util                        {version=3.0.7}

[CAPABILITIES]

Provide-Capability
  osgi.service                           {objectClass=org.evrete.api.spi.ExpressionResolverProvider, effective:=active}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.ExpressionResolverProvider, register:=org.evrete.spi.minimal.DefaultExpressionResolverProvider}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.LiteralRhsCompiler, register:=org.evrete.spi.minimal.DefaultLiteralRhsCompiler}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.MemoryFactoryProvider, register:=org.evrete.spi.minimal.DefaultMemoryFactoryProvider}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.TypeResolverProvider, register:=org.evrete.spi.minimal.DefaultTypeResolverProvider}
  osgi.service                           {objectClass=org.evrete.api.spi.LiteralRhsCompiler, effective:=active}
  osgi.service                           {objectClass=org.evrete.api.spi.MemoryFactoryProvider, effective:=active}
  osgi.service                           {objectClass=org.evrete.api.spi.TypeResolverProvider, effective:=active}
Require-Capability
  osgi.ee                                {filter:=(&(osgi.ee=JavaSE)(version=1.8))}
  osgi.extender                          {filter:=(&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0)))}
  osgi.extender                          {filter:=(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!(version>=2.0.0)))}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.DSLKnowledgeProvider), osgi.serviceloader=org.evrete.api.spi.DSLKnowledgeProvider}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.ExpressionResolverProvider), osgi.serviceloader=org.evrete.api.spi.ExpressionResolverProvider}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.LiteralRhsCompiler), osgi.serviceloader=org.evrete.api.spi.LiteralRhsCompiler}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.MemoryFactoryProvider), osgi.serviceloader=org.evrete.api.spi.MemoryFactoryProvider}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.TypeResolverProvider), osgi.serviceloader=org.evrete.api.spi.TypeResolverProvider}

[COMPONENTS]



[METATYPE]



[API USES]


[USES]

org.evrete                              org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.runtime
                                        org.evrete.runtime.async
org.evrete.api                          org.evrete
                                        org.evrete.runtime
                                        org.evrete.runtime.compiler
org.evrete.api.annotations              
org.evrete.api.spi                      org.evrete
                                        org.evrete.api
                                        org.evrete.runtime.compiler
org.evrete.collections                  org.evrete.api
                                        org.evrete.util
org.evrete.runtime                      org.evrete
                                        org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.collections
                                        org.evrete.runtime.async
                                        org.evrete.runtime.compiler
                                        org.evrete.runtime.evaluation
                                        org.evrete.util
org.evrete.runtime.async                org.evrete.api
                                        org.evrete.collections
                                        org.evrete.runtime
                                        org.evrete.runtime.evaluation
                                        org.evrete.util
org.evrete.runtime.compiler             javax.lang.model.element
                                        javax.tools
                                        org.evrete.api
                                        org.evrete.util
org.evrete.runtime.evaluation           org.evrete.api
                                        org.evrete.runtime
                                        org.evrete.util
org.evrete.spi.minimal                  org.evrete
                                        org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.collections
                                        org.evrete.runtime
                                        org.evrete.runtime.compiler
                                        org.evrete.util
org.evrete.util                         org.evrete
                                        org.evrete.api
                                        org.evrete.runtime
                                        org.evrete.runtime.evaluation


[USEDBY]

javax.lang.model.element                org.evrete.runtime.compiler
javax.tools                             org.evrete.runtime.compiler
org.evrete                              org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.runtime
                                        org.evrete.spi.minimal
                                        org.evrete.util
org.evrete.api                          org.evrete
                                        org.evrete.api.spi
                                        org.evrete.collections
                                        org.evrete.runtime
                                        org.evrete.runtime.async
                                        org.evrete.runtime.compiler
                                        org.evrete.runtime.evaluation
                                        org.evrete.spi.minimal
                                        org.evrete.util
org.evrete.api.spi                      org.evrete
                                        org.evrete.runtime
                                        org.evrete.spi.minimal
org.evrete.collections                  org.evrete.runtime
                                        org.evrete.runtime.async
                                        org.evrete.spi.minimal
org.evrete.runtime                      org.evrete
                                        org.evrete.api
                                        org.evrete.runtime.async
                                        org.evrete.runtime.evaluation
                                        org.evrete.spi.minimal
                                        org.evrete.util
org.evrete.runtime.async                org.evrete
                                        org.evrete.runtime
org.evrete.runtime.compiler             org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.runtime
                                        org.evrete.spi.minimal
org.evrete.runtime.evaluation           org.evrete.runtime
                                        org.evrete.runtime.async
                                        org.evrete.util
org.evrete.util                         org.evrete.collections
                                        org.evrete.runtime
                                        org.evrete.runtime.async
                                        org.evrete.runtime.compiler
                                        org.evrete.runtime.evaluation
                                        org.evrete.spi.minimal


```  
---
Core Manifest - Plain:
```
Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.3.0
Build-Jdk-Spec: 22
Bundle-Description: Java Rule Engine
Bundle-DocURL: https://www.evrete.org/evrete-core
Bundle-License: "MIT License";link="https://www.opensource.org/licenses/
 mit-license"
Bundle-ManifestVersion: 2
Bundle-Name: evrete-core
Bundle-SCM: url="https://github.com/evrete/evrete/evrete-core",connectio
 n="scm:git:https://github.com/evrete/evrete.git/evrete-core",developer-
 connection="scm:git:https://github.com/evrete/evrete.git/evrete-core",t
 ag=HEAD
Bundle-SymbolicName: evrete-core
Bundle-Version: 3.0.7.202402081653
Export-Package: org.evrete;uses:="org.evrete.api,org.evrete.api.spi,org.
 evrete.runtime.async";version="3.0.7",org.evrete.api;uses:="org.evrete,
 org.evrete.runtime,org.evrete.runtime.compiler";version="3.0.7",org.evr
 ete.api.annotations;version="3.0.7",org.evrete.api.spi;uses:="org.evret
 e,org.evrete.api,org.evrete.runtime.compiler";version="3.0.7",org.evret
 e.collections;uses:="org.evrete.api";version="3.0.7",org.evrete.runtime
 ;uses:="org.evrete,org.evrete.api,org.evrete.collections,org.evrete.run
 time.compiler,org.evrete.runtime.evaluation,org.evrete.util";version="3
 .0.7",org.evrete.runtime.async;uses:="org.evrete.runtime,org.evrete.run
 time.evaluation,org.evrete.util";version="3.0.7",org.evrete.runtime.com
 piler;uses:="javax.lang.model.element,javax.tools,org.evrete.api";versi
 on="3.0.7",org.evrete.runtime.evaluation;uses:="org.evrete.api,org.evre
 te.runtime,org.evrete.util";version="3.0.7",org.evrete.spi.minimal;uses
 :="org.evrete.api,org.evrete.api.spi,org.evrete.runtime.compiler";versi
 on="3.0.7",org.evrete.util;uses:="org.evrete,org.evrete.api,org.evrete.
 runtime,org.evrete.runtime.evaluation";version="3.0.7"
Implementation-Title: Java Rule Engine
Implementation-URL: https://www.evrete.org
Implementation-Version: 3.0.07-SNAPSHOT
Import-Package: javax.lang.model.element,javax.tools,org.evrete,org.evre
 te.api,org.evrete.api.spi,org.evrete.collections,org.evrete.runtime,org
 .evrete.runtime.async,org.evrete.runtime.compiler,org.evrete.runtime.ev
 aluation,org.evrete.util
Provide-Capability: osgi.service;objectClass:List<String>="org.evrete.ap
 i.spi.ExpressionResolverProvider";effective:=active,osgi.service;object
 Class:List<String>="org.evrete.api.spi.LiteralRhsCompiler";effective:=a
 ctive,osgi.service;objectClass:List<String>="org.evrete.api.spi.MemoryF
 actoryProvider";effective:=active,osgi.service;objectClass:List<String>
 ="org.evrete.api.spi.TypeResolverProvider";effective:=active,osgi.servi
 celoader;osgi.serviceloader="org.evrete.api.spi.ExpressionResolverProvi
 der";register:="org.evrete.spi.minimal.DefaultExpressionResolverProvide
 r",osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.LiteralRhs
 Compiler";register:="org.evrete.spi.minimal.DefaultLiteralRhsCompiler",
 osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.MemoryFactory
 Provider";register:="org.evrete.spi.minimal.DefaultMemoryFactoryProvide
 r",osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.TypeResolv
 erProvider";register:="org.evrete.spi.minimal.DefaultTypeResolverProvid
 er"
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.service
 loader.processor)(version>=1.0.0)(!(version>=2.0.0)))",osgi.extender;fi
 lter:="(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!
 (version>=2.0.0)))",osgi.serviceloader;filter:="(osgi.serviceloader=org
 .evrete.api.spi.DSLKnowledgeProvider)";osgi.serviceloader="org.evrete.a
 pi.spi.DSLKnowledgeProvider",osgi.serviceloader;filter:="(osgi.servicel
 oader=org.evrete.api.spi.ExpressionResolverProvider)";osgi.serviceloade
 r="org.evrete.api.spi.ExpressionResolverProvider",osgi.serviceloader;fi
 lter:="(osgi.serviceloader=org.evrete.api.spi.LiteralRhsCompiler)";osgi
 .serviceloader="org.evrete.api.spi.LiteralRhsCompiler",osgi.serviceload
 er;filter:="(osgi.serviceloader=org.evrete.api.spi.MemoryFactoryProvide
 r)";osgi.serviceloader="org.evrete.api.spi.MemoryFactoryProvider",osgi.
 serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.TypeResol
 verProvider)";osgi.serviceloader="org.evrete.api.spi.TypeResolverProvid
 er",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
SPDX-License-Identifier: MIT License

  ```

### CODE REVIEW

**Comment by stbischof** [comment]
This shows the patter how to handle it, without annotations.

If this matches more your expectations would be nice to discuss:
- which packages you want to export/ which should be private
- are there any expectation  from the user that also want OSGi-Support, we could address that

**Comment by stbischof** [comment]
current [TEST-evrete-core.xml](https://github.com/evrete/evrete/files/14214335/TEST-evrete-core-3.0.7.202402082022.zip)

**Comment by andbi** [comment]
@stbischof, hi again.

Before I close these requests, I'd like to provide some explanations.

We're math guys; we’re good at implementing very specific forward-chaining algorithms and nothing else. We're much like the guys behind the Apache Commons Math library. We’re not supposed to even know about OSGi, let alone supporting its dependencies. The reason I personally know about OSGi is that I’ve spent almost 25 years in IT and I’ve seen things.

Now, I certainly appreciate your eagerness and persistence in whatever you and @timothyjward are working on, but this is not how the Java world operates. Essentially, what you're asking us is:

> Hey math guys!
> 
> You're proficient with ABC, while I'm good at XYZi. You might not even know what that is, but I need it included in your library. I know that you support ABC in your free time, so here's an additional task for you. 
> 
> Now, not only do you need to find someone to support these XYZi dependencies, but you also need a backup in case the original person gets hit by a bus. 
> 
> POM dependencies need to be up-to-date, tests must succeed, and you also have to educate yourselves about XYZi and understand how cool it is.
> 

However, this is not how things work. You can't just impose your dependencies on any library you need in your project. My guess is that you’re in the middle of some miscommunication, misunderstanding, or mismanagement.

**Comment by stbischof** [comment]
Just to make some points clear.

The goal of my PR's was and is to inform you about the need if others to use you lib in a osgi Setup. And not just to ask for Support but also to come up with solutuons.

This pr has 2 commits.

The First one in the one that i wanted to bring in your Manifest as an Alternative to to the annotations. We had in the other PR.


The second commit is just to Show and discuss what would be if we run all tests in an osgi Framework. This will not be part of a pr that is not in draft Mode.

**Comment by andbi** [comment]
@stbischof, you do not need to patch the 'apache.commons.math3' library's POM to use it within an OSGi environment, right?

Therefore, my original question was, what is preventing you from using Evrete as it is? Are you facing any problems, exceptions, or class loading issues? Could you please provide specific details about them?

I am willing to help resolve these issues, but the library stays independent of third-party frameworks and their dependencies.

**Comment by timothyjward** [comment]
> However, this is not how things work. You can't just impose your dependencies on any library you need in your project.

Hi @andbi - I apologise on our behalf for the sudden influx of Pull Requests. I had hoped to discuss and agree an approach before any actual contribution was started. It is certainly not our intent to impose dependencies on this (or any other) project. This is a packaging request as much as anything else, in much the same way as the maven artifacts already include maven metadata in META-INF and the manifests contain additional headers written by the Evrete team.

To answer the following:

> @stbischof, you do not need to patch the 'apache.commons.math3' library's POM to use it within an OSGi environment, right?

No, but this is because Apache Commons Math 3 includes OSGi metadata in its manifest, i.e. it is an OSGi bundle. This is what we are requesting Evrete to provide. 
It would be possible to repackage the Evrete code with the updated manifest file in the open source project where we want to use it (Eclipse sensiNact) but that introduces a mixture of licensing questions (Eclipse sensiNact is EPL, which isn't the same as Evrete) and namespacing issues (is it ok to re-release Evrete in an Eclipse namespace?). 

This isn't even an OSGi-specific problem space. Apache Commons Math 3 also includes module metadata for the Java Platform Module System, for exactly the same reason of deployability and reuse.

> Therefore, my original question was, what is preventing you from using Evrete as it is?

The thing currently preventing us from using Evrete is that there is no OSGi metadata in the jar manifest. This means that when Evrete is installed into an OSGi framework no packages are provided for use by other OSGi bundles, and no package imports are declared so no classes can be loaded. This metadata is usually generated automatically from the code using a maven plugin such as `bnd-maven-plugin`.

**Comment by andbi** [comment]
@timothyjward, thanks and apologies to you and @stbischof - I was obviously wrong about the Math3 metadata. And It changes a lot. 

A new version of Evrete  is set to be released this week. Following that, I intend to learn more about modern OSGi, as I've clearly fallen behind. I will look at how the Apache math team handles their POMs and reproduce their approach. The ETA is 1-2 weeks tops since I'm currently traveling. You have my word it will be done, hopefully with your help.

What's confusing me now, even with my level of understanding of OSGi, is that @stbischof provided metadata for each Service Provider SPI implementation instead of declaring them once on the service provider interfaces. 
At first sight, it makes sense, but it also seems like an obvious job for the OSGi framework itself.

**Comment by andbi** [comment]
@timothyjward, @stbischof, Please disregard the last paragraph. I've found the root problem explained here: https://aries.apache.org/documentation/modules/spi-fly.html

**Comment by stbischof** [comment]
Great. The aries Site is a good source. 

Helped me also a lot to understand this a bit better.

So some more input that may is interesting.

Commons-math uses the commons-parent as a parent pom.
in this parent pom they use the Felix-Bunde-Plugin to generate the Manifest.

https://github.com/apache/commons-parent/blob/4ac50dbe0a56a6fa0996f01aae407ef24b0e2765/pom.xml#L989


Felix-Bunde-Plugin is a Plugin from the apache Felix Project, which provied a lot of Implementations for osgi.

But the felix-bundle-plugin is just a wrapper around the bnd-maven-plugin. 

https://github.com/apache/felix-dev/blob/e479f6517c4bcbf5fcdd73c20b8760fe1610ab3a/tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/BundlePlugin.java#L113

Thats why i used the bnd.


There are 2 and a half main Options to generate the Manifest an osgi Framework would need.

- annotations in code that are not relevant at runtime
- instructions to the maven plugin  Bundle-SymbilicName/ imports/exports.
- write some parts, that do not often change manually



So before we go deeper.
So you have more questions/ would we provide more information on some parts?

**Comment by andbi** [comment]
@stbischof, Your last PRs with POM updates seem like a good start for now. It would be great if you reopened them as a single PR (sorry), but again, I won't be able to merge it until after the next release.

**Comment by stbischof** [comment]
Juat to have it right, you mean the Version without annotations?

And just First commit of this PR:

https://github.com/evrete/evrete/commit/93f570e0cec688e189d7eef6ffdce9979581b53f

Plus a fix that i found while i played with the Testsetup. But Testsetup will not be part of the commit.


I am fine with the Timeline.  Do your release with your Things. And when time is come to merge the osgi support we will have what we need.

**Comment by andbi** [comment]
Please include tests as well. The new OSGi support is an obligation, and obligations must be tested. Additionally they will help us get a better understanding of what we've just gotten ourselves into😀

**Comment by timothyjward** [comment]
> Please include tests as well.

Would you like the OSGi tests to be included in a different build artifact? Putting OSGi tests in the existing artifacts has the advantage that the tests will always be run by someone making changes, and it will be clear if/when a change has made a test fail. On the other hand a separate artifact can be excluded from deployment (there's no need to put it in Maven Central) and it would help to guarantee your "no external dependencies" rules aren't broken, even for tests.

**Comment by andbi** [comment]
@qtimothyjward Good point. How about a separate module, say 'core-osgi', or whatever the naming conventions/good practices are.

**Pull request closed without merging**
