### PR TITLE
OSGi Support - Annotation

### PR DESCRIPTION
**Pull request by stbischof**
I would like to use evrete inside an [OSGi](https://www.osgi.org/resources/where-to-start/) Runtime.
For this it is important to have proper Bundle-Manifest Metadata.

Since writing Manifests could be very complex we generate then using `bnd-maven-plugin` that analyses code and the annotations from `bnd.annotations` and `orgs.osgi.annotations.bundle`.

At the Moment this PR does:

- generate Bundle-Manifests
- export packages to use for others
- ServiceLoader (@ServiceProvider,@ServiceConsumer)
  - generate ServiceLoader-Files
  - generate OSGI-Metadata for Services
  - generate OSGi- Require-Cap (osgi.service.processor and registrar)

@timothyjward: could you review this first draft?

Manifests in Print-Mode

evrete-core
```
 
[MANIFEST]

Build-Jdk-Spec                          22
Bundle-Description                      Java Rule Engine
Bundle-DocURL                           https://www.evrete.org/evrete-core
Bundle-License                          "MIT License";link="https://www.opensource.org/licenses/mit-license"
Bundle-ManifestVersion                  2
Bundle-Name                             evrete-core
Bundle-SCM                              connection="scm:git:https://github.com/evrete/evrete.git/evrete-core"
                                        developer-connection="scm:git:https://github.com/evrete/evrete.git/evrete-core"
                                        tag=HEAD
                                        url="https://github.com/evrete/evrete/evrete-core"
Bundle-SymbolicName                     evrete-core
Bundle-Version                          3.0.7.202402071523
Created-By                              Maven JAR Plugin 3.3.0
Export-Package                          org.evrete.api.annotations;version="3.0.7"
                                        org.evrete.api.spi;uses:="org.evrete,org.evrete.api,org.evrete.runtime.compiler";version="3.0.7"
                                        org.evrete.api;uses:="org.evrete,org.evrete.runtime,org.evrete.runtime.compiler";version="3.0.7"
                                        org.evrete.collections;version="0.0.1";uses:="org.evrete.api"
                                        org.evrete.runtime.async;uses:="org.evrete.runtime,org.evrete.runtime.evaluation";version="3.0.7"
                                        org.evrete.runtime.compiler;uses:="javax.lang.model.element,javax.tools,org.evrete.api";version="3.0.7"
                                        org.evrete.runtime.evaluation;uses:="org.evrete.api,org.evrete.runtime";version="3.0.7"
                                        org.evrete.runtime;uses:="org.evrete,org.evrete.api,org.evrete.collections,org.evrete.runtime.compiler,org.evrete.runtime.evaluation";version="3.0.7"
                                        org.evrete.spi.minimal;uses:="org.evrete.api,org.evrete.api.spi,org.evrete.runtime.compiler";version="3.0.7"
                                        org.evrete;uses:="org.evrete.api,org.evrete.api.spi,org.evrete.runtime.async";version="3.0.7"
Implementation-Title                    Java Rule Engine
Implementation-URL                      https://www.evrete.org
Implementation-Version                  3.0.07-SNAPSHOT
Import-Package                          java.io
                                        java.lang
                                        java.lang.annotation
                                        java.lang.invoke
                                        java.lang.reflect
                                        java.net
                                        java.nio.charset
                                        java.nio.file
                                        java.nio.file.spi
                                        java.util
                                        java.util.concurrent
                                        java.util.concurrent.atomic
                                        java.util.function
                                        java.util.jar
                                        java.util.logging
                                        java.util.regex
                                        java.util.stream
                                        java.util.zip
                                        javax.lang.model.element
                                        javax.tools
                                        org.evrete
                                        org.evrete.api
                                        org.evrete.api.spi
Manifest-Version                        1.0
Private-Package                         org.evrete.util
Provide-Capability                      osgi.service;objectClass:List<String>="org.evrete.api.spi.ExpressionResolverProvider";effective:=active
                                        osgi.service;objectClass:List<String>="org.evrete.api.spi.LiteralRhsCompiler";effective:=active
                                        osgi.service;objectClass:List<String>="org.evrete.api.spi.MemoryFactoryProvider";effective:=active
                                        osgi.service;objectClass:List<String>="org.evrete.api.spi.TypeResolverProvider";effective:=active
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.ExpressionResolverProvider";register:="org.evrete.spi.minimal.DefaultExpressionResolverProvider"
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.LiteralRhsCompiler";register:="org.evrete.spi.minimal.DefaultLiteralRhsCompiler"
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.MemoryFactoryProvider";register:="org.evrete.spi.minimal.DefaultMemoryFactoryProvider"
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.TypeResolverProvider";register:="org.evrete.spi.minimal.DefaultTypeResolverProvider"
Require-Capability                      osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
                                        osgi.extender;filter:="(&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0)))"
                                        osgi.extender;filter:="(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!(version>=2.0.0)))"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.DSLKnowledgeProvider)";osgi.serviceloader="org.evrete.api.spi.DSLKnowledgeProvider"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.ExpressionResolverProvider)";osgi.serviceloader="org.evrete.api.spi.ExpressionResolverProvider"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.LiteralRhsCompiler)";osgi.serviceloader="org.evrete.api.spi.LiteralRhsCompiler"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.MemoryFactoryProvider)";osgi.serviceloader="org.evrete.api.spi.MemoryFactoryProvider"
                                        osgi.serviceloader;filter:="(osgi.serviceloader=org.evrete.api.spi.TypeResolverProvider)";osgi.serviceloader="org.evrete.api.spi.TypeResolverProvider"
SPDX-License-Identifier                 MIT License


[IMPEXP]

Import-Package
  java.io                                
  java.lang                              
  java.lang.annotation                   
  java.lang.invoke                       
  java.lang.reflect                      
  java.net                               
  java.nio.charset                       
  java.nio.file                          
  java.nio.file.spi                      
  java.util                              
  java.util.concurrent                   
  java.util.concurrent.atomic            
  java.util.function                     
  java.util.jar                          
  java.util.logging                      
  java.util.regex                        
  java.util.stream                       
  java.util.zip                          
  javax.lang.model.element               
  javax.tools                            
  org.evrete                             
  org.evrete.api                         
  org.evrete.api.spi                     

Export-Package
  org.evrete                             {version=3.0.7}
  org.evrete.api                         {version=3.0.7}
  org.evrete.api.annotations             {version=3.0.7}
  org.evrete.api.spi                     {version=3.0.7}
  org.evrete.collections                 {version=0.0.1}
  org.evrete.runtime                     {version=3.0.7}
  org.evrete.runtime.async               {version=3.0.7}
  org.evrete.runtime.compiler            {version=3.0.7}
  org.evrete.runtime.evaluation          {version=3.0.7}
  org.evrete.spi.minimal                 {version=3.0.7}

[CAPABILITIES]

Provide-Capability
  osgi.service                           {objectClass=org.evrete.api.spi.ExpressionResolverProvider, effective:=active}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.ExpressionResolverProvider, register:=org.evrete.spi.minimal.DefaultExpressionResolverProvider}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.LiteralRhsCompiler, register:=org.evrete.spi.minimal.DefaultLiteralRhsCompiler}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.MemoryFactoryProvider, register:=org.evrete.spi.minimal.DefaultMemoryFactoryProvider}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.TypeResolverProvider, register:=org.evrete.spi.minimal.DefaultTypeResolverProvider}
  osgi.service                           {objectClass=org.evrete.api.spi.LiteralRhsCompiler, effective:=active}
  osgi.service                           {objectClass=org.evrete.api.spi.MemoryFactoryProvider, effective:=active}
  osgi.service                           {objectClass=org.evrete.api.spi.TypeResolverProvider, effective:=active}
Require-Capability
  osgi.ee                                {filter:=(&(osgi.ee=JavaSE)(version=1.8))}
  osgi.extender                          {filter:=(&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0)))}
  osgi.extender                          {filter:=(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!(version>=2.0.0)))}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.DSLKnowledgeProvider), osgi.serviceloader=org.evrete.api.spi.DSLKnowledgeProvider}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.ExpressionResolverProvider), osgi.serviceloader=org.evrete.api.spi.ExpressionResolverProvider}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.LiteralRhsCompiler), osgi.serviceloader=org.evrete.api.spi.LiteralRhsCompiler}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.MemoryFactoryProvider), osgi.serviceloader=org.evrete.api.spi.MemoryFactoryProvider}
  osgi.serviceloader                     {filter:=(osgi.serviceloader=org.evrete.api.spi.TypeResolverProvider), osgi.serviceloader=org.evrete.api.spi.TypeResolverProvider}

[COMPONENTS]



[METATYPE]



[API USES]


[USES]

org.evrete                              org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.runtime
                                        org.evrete.runtime.async
org.evrete.api                          org.evrete
                                        org.evrete.runtime
                                        org.evrete.runtime.compiler
org.evrete.api.annotations              
org.evrete.api.spi                      org.evrete
                                        org.evrete.api
                                        org.evrete.runtime.compiler
org.evrete.collections                  org.evrete.api
                                        org.evrete.util
org.evrete.runtime                      org.evrete
                                        org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.collections
                                        org.evrete.runtime.async
                                        org.evrete.runtime.compiler
                                        org.evrete.runtime.evaluation
                                        org.evrete.util
org.evrete.runtime.async                org.evrete.api
                                        org.evrete.collections
                                        org.evrete.runtime
                                        org.evrete.runtime.evaluation
                                        org.evrete.util
org.evrete.runtime.compiler             javax.lang.model.element
                                        javax.tools
                                        org.evrete.api
                                        org.evrete.util
org.evrete.runtime.evaluation           org.evrete.api
                                        org.evrete.runtime
                                        org.evrete.util
org.evrete.spi.minimal                  org.evrete
                                        org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.collections
                                        org.evrete.runtime
                                        org.evrete.runtime.compiler
                                        org.evrete.util
org.evrete.util                         org.evrete
                                        org.evrete.api
                                        org.evrete.runtime
                                        org.evrete.runtime.evaluation
```
---
org.evrete.dsl
```
[MANIFEST]

Build-Jdk-Spec                          22
Bundle-Description                      Java Rule Engine
Bundle-DocURL                           https://www.evrete.org/evrete-dsl-java
Bundle-License                          "MIT License";link="https://www.opensource.org/licenses/mit-license"
Bundle-ManifestVersion                  2
Bundle-Name                             evrete-dsl-java
Bundle-SCM                              connection="scm:git:https://github.com/evrete/evrete.git/evrete-dsl-java"
                                        developer-connection="scm:git:https://github.com/evrete/evrete.git/evrete-dsl-java"
                                        tag=HEAD
                                        url="https://github.com/evrete/evrete/evrete-dsl-java"
Bundle-SymbolicName                     evrete-dsl-java
Bundle-Version                          3.0.7.202402071523
Created-By                              Maven JAR Plugin 3.3.0
Export-Package                          org.evrete.dsl.annotation;uses:="org.evrete.dsl";version="3.0.7"
                                        org.evrete.dsl;uses:="org.evrete,org.evrete.api";version="3.0.7"
Implementation-Title                    Java Rule Engine
Implementation-URL                      https://www.evrete.org
Implementation-Version                  3.0.07-SNAPSHOT
Import-Package                          java.io
                                        java.lang
                                        java.lang.annotation
                                        java.lang.invoke
                                        java.lang.reflect
                                        java.net
                                        java.nio.charset
                                        java.util
                                        java.util.concurrent
                                        java.util.function
                                        java.util.jar
                                        java.util.logging
                                        org.evrete.api.spi;version="[3.0,4)"
                                        org.evrete.api;version="[3.0,4)"
                                        org.evrete.dsl
                                        org.evrete.dsl.annotation
                                        org.evrete.runtime.compiler;version="[3.0,4)"
                                        org.evrete.util
                                        org.evrete;version="[3.0,4)"
Manifest-Version                        1.0
Provide-Capability                      osgi.service;objectClass:List<String>="org.evrete.api.spi.DSLKnowledgeProvider";effective:=active
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.DSLKnowledgeProvider";register:="org.evrete.dsl.DSLClassProvider"
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.DSLKnowledgeProvider";register:="org.evrete.dsl.DSLJarProvider"
                                        osgi.serviceloader;osgi.serviceloader="org.evrete.api.spi.DSLKnowledgeProvider";register:="org.evrete.dsl.DSLSourceProvider"
Require-Capability                      osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
                                        osgi.extender;filter:="(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!(version>=2.0.0)))"
SPDX-License-Identifier                 MIT License


[IMPEXP]

Import-Package
  java.io                                
  java.lang                              
  java.lang.annotation                   
  java.lang.invoke                       
  java.lang.reflect                      
  java.net                               
  java.nio.charset                       
  java.util                              
  java.util.concurrent                   
  java.util.function                     
  java.util.jar                          
  java.util.logging                      
  org.evrete                             {version=[3.0,4)}
  org.evrete.api                         {version=[3.0,4)}
  org.evrete.api.spi                     {version=[3.0,4)}
  org.evrete.dsl                         
  org.evrete.dsl.annotation              
  org.evrete.runtime.compiler            {version=[3.0,4)}
  org.evrete.util                        

Export-Package
  org.evrete.dsl                         {version=3.0.7}
  org.evrete.dsl.annotation              {version=3.0.7}

[CAPABILITIES]

Provide-Capability
  osgi.service                           {objectClass=org.evrete.api.spi.DSLKnowledgeProvider, effective:=active}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.DSLKnowledgeProvider, register:=org.evrete.dsl.DSLClassProvider}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.DSLKnowledgeProvider, register:=org.evrete.dsl.DSLJarProvider}
  osgi.serviceloader                     {osgi.serviceloader=org.evrete.api.spi.DSLKnowledgeProvider, register:=org.evrete.dsl.DSLSourceProvider}
Require-Capability
  osgi.ee                                {filter:=(&(osgi.ee=JavaSE)(version=1.8))}
  osgi.extender                          {filter:=(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!(version>=2.0.0)))}

[COMPONENTS]



[METATYPE]



[API USES]


[USES]

org.evrete.dsl                          org.evrete
                                        org.evrete.api
                                        org.evrete.api.spi
                                        org.evrete.dsl.annotation
                                        org.evrete.runtime.compiler
                                        org.evrete.util
org.evrete.dsl.annotation               org.evrete.dsl


```
---
evrete-jsr94
```
[MANIFEST]

Build-Jdk-Spec                          22
Bundle-Description                      Java Rule Engine
Bundle-DocURL                           https://www.evrete.org/evrete-jsr94
Bundle-License                          "MIT License";link="https://www.opensource.org/licenses/mit-license"
Bundle-ManifestVersion                  2
Bundle-Name                             evrete-jsr94
Bundle-SCM                              connection="scm:git:https://github.com/evrete/evrete.git/evrete-jsr94"
                                        developer-connection="scm:git:https://github.com/evrete/evrete.git/evrete-jsr94"
                                        tag=HEAD
                                        url="https://github.com/evrete/evrete/evrete-jsr94"
Bundle-SymbolicName                     evrete-jsr94
Bundle-Version                          3.0.7.202402071523
Created-By                              Maven JAR Plugin 3.3.0
Export-Package                          org.evrete.jsr94;uses:="javax.rules,javax.rules.admin";version="3.0.7"
Implementation-Title                    Java Rule Engine
Implementation-URL                      https://www.evrete.org
Implementation-Version                  3.0.07-SNAPSHOT
Import-Package                          java.io
                                        java.lang
                                        java.lang.invoke
                                        java.net
                                        java.util
                                        java.util.concurrent
                                        java.util.function
                                        java.util.logging
                                        java.util.stream
                                        javax.rules
                                        javax.rules.admin
                                        org.evrete.api;version="[3.0,4)"
                                        org.evrete.runtime;version="[3.0,4)"
                                        org.evrete;version="[3.0,4)"
                                        org.w3c.dom
Manifest-Version                        1.0
Require-Capability                      osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
SPDX-License-Identifier                 MIT License


[IMPEXP]

Import-Package
  java.io                                
  java.lang                              
  java.lang.invoke                       
  java.net                               
  java.util                              
  java.util.concurrent                   
  java.util.function                     
  java.util.logging                      
  java.util.stream                       
  javax.rules                            
  javax.rules.admin                      
  org.evrete                             {version=[3.0,4)}
  org.evrete.api                         {version=[3.0,4)}
  org.evrete.runtime                     {version=[3.0,4)}
  org.w3c.dom                            

Export-Package
  org.evrete.jsr94                       {version=3.0.7}

[CAPABILITIES]

Require-Capability
  osgi.ee                                {filter:=(&(osgi.ee=JavaSE)(version=1.8))}

[COMPONENTS]



[METATYPE]



[API USES]


[USES]

org.evrete.jsr94                        javax.rules
                                        javax.rules.admin
                                        org.evrete
                                        org.evrete.api
                                        org.evrete.runtime
                                        org.w3c.dom

```

### CODE REVIEW

**Comment by andbi** [comment]
Hi!

That's quite a serious request. It's been quite a long time since I've dealt with OSGi, and, correct me if I'm wrong, but the framework allows to turn basically any Java module into an OSGI bundle in a declarative way using manifests and w/o any changes to the underlying code.

Evrete's policy is to be a vanilla Java library with zero dependencies. The only third party dependencies you'll see in the library's pom are in the benchmark or examples sub-modules.

Now about the request and possible workarounds:

1. Changes to the SPI implementations aren't necessary because you can provide your own implementations by simply extending the existing ones and use the proposed OSGI annotations on your classes.

2. The same goes for the POMs. One can create a standalone POM that will do the packaging and other OSGI-related jobs.

3. Annotating the core library APIs is definitely a no-go, there must be a way to achieve the same goal either by wrapping the library or by using OSGI declarations.

Regards,

andbi

**Comment by timothyjward** [comment]
> @timothyjward: could you review this first draft?

I’d be very happy to help with this, either by reviewing or helping with contributions.

> It's been quite a long time since I've dealt with OSGi, and, correct me if I'm wrong, but the framework allows to turn basically any Java module into an OSGI bundle in a declarative way using manifests and w/o any changes to the underlying code.

Broadly speaking this is correct. It can be more challenging for some modules that play around with classloaders to get visibility of things at runtime, but I don’t believe that will apply here. 

Just a few quick checks so we can come up with the best approach.

> Changes to the SPI implementations aren't necessary because you can provide your own implementations by simply extending the existing ones and use the proposed OSGI annotations on your classes.

Just to confirm - are you expecting that there would be new build artifacts for these, or just new types in the existing jar files?

> The same goes for the POMs. One can create a standalone POM that will do the packaging and other OSGI-related jobs.

Do you mean that adding a maven plugin to an existing pom to generate the additional manifest data is a non-starter?

> Annotating the core library APIs is definitely a no-go, there must be a way to achieve the same goal either by wrapping the library or by using OSGI declarations.

Would it change your opinion if the annotations were class retention and therefore not visible (either as a dependency or on the types) at runtime?

**Comment by andbi** [comment]
> Just a few quick checks so we can come up with the best approach.

That's what I'm aiming for. 

However, before we delve into the programming aspects, allow me to describe the zero-dependency feature. Just earlier today, I had a conversation with a user who selected the library mainly because it's a plain vanilla Java library without any dependencies, eliminating typical legal complexities often associated with them.

They also brought up OSGI, so this pull request came precisely on time. I really hope that we can find a common ground on this matter.

Here's my suggestion to them, which you might find suitable for your use case:

If it's a domain-specific task, creating an abstraction layer and packaging Evrete within it could be beneficial. This is generally good practice, with the following pros and cons:

Pros:
1. It makes the project less dependent on the implementation of the rule engine; thereby creating the potential to switch to Drools or any other available engine in the future. The OSGI annotations are placed on the wrapper classes and are fully under your control.

2. It negates the need to alter the engine's code, and the proposed OSGI annotations will not cause any problems if **other users already have the library packaged into OSGI bundles**. 

3. The abstraction has its own POM where you can dissect and repackage Evrete in any way you need. 

Cons:
1. Possible class loading issues. You're absolutely correct in this regard. The library is essentially made up of SPI implementations, and, historically, SPI and OSGI do not coexist smoothly. However, the silver lining to this con is that we can collectively troubleshoot these issues one by one and make the library truly OSGI-ready. I'm totally on your side here.

2. Aside from potential classloading issues, there's another problem we'll probably need to address. The library compiles and adds classes to JVM on the fly, turning each literal condition into a Java class in a dedicated package. Frankly, I don't remember how this behavior is compatible with the OSGI framework.

**Comment by stbischof** [comment]
Just to get some general things right:
- A change in the Manifest is not a Problem
- Annotations are critical, because would not like to depent on them on runtime.

The Annotations we use do not anything on Runtime. [RetentionPolicy](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/RetentionPolicy.html) [Class](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/RetentionPolicy.html#CLASS)
They are only there for processing on the build to:
- calculate/generate the Manifest.
- generate the ServiceLoader Files that I deleted in this PR

The Annotations are:
[ServiceConsumer](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.annotation/src/aQute/bnd/annotation/spi/ServiceConsumer.java)
[ServiceProvider](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.annotation/src/aQute/bnd/annotation/spi/ServiceProvider.java)
[Export](https://github.com/osgi/osgi/blob/main/org.osgi.annotation.bundle/src/org/osgi/annotation/bundle/Export.java)

**Comment by stbischof** [comment]
Just a Side-Question:

Since you seems to care a lot about the quality of your bundle:
What are your opinions about:
[Semantic Versioning](https://semver.org/lang/de/) (of Jars and Packages)

There would be a way using [Version-Annotations](https://bnd.bndtools.org/chapters/170-versioning.html) to declare the versions and verify changes using [bnd-baseline-maven-plugin](https://github.com/bndtools/bnd/tree/master/maven-plugins/bnd-baseline-maven-plugin)

**Comment by andbi** [comment]
> To run the evrete lib nobody needs more then the just the lib. No bnd.annotations and org.osgi.annotations.bundle needes on classpath.

That's true. Annotations represent meta info and won't throw any exceptions if not available on the class path. But users will still need them to compile the library and they will show up as dependencies.

I'm sorry, but I still don't see a convincing reason to either break the commitments the library has made to its users or force them to comply with stricter licensing terms, specifically Apache 2.0 in this case. I hope this is understandable.

If annotating the Evrete classes is absolutely necessary, and the suggested idea of abstraction layers/wrappers isn't suitable in your case, you always have the option to run a preprocessor on the sources to have them annotated in your way.

**Comment by stbischof** [comment]
#80  shows the  manual version without Annotations

**Pull request closed without merging**
